schema_version: 1

context:
  version: "260821"

package:
  name: msglc
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/m/msglc/msglc-${{ version }}.tar.gz
  sha256: e430bb0eeaa70606e7e3796bdf911168e91913dfa30c123174b86149c60b071e

build:
  number: 0
  skip: match(python, "<3.11")
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler("rust") }}
    - cargo-bundle-licenses
  host:
    - python
    - maturin >=1
    - cython
    - pip
    - puccinialin
  run:
    - python
    - bitarray
    - cbor2
    - msgpack-python >=1
    - universal-pathlib

tests:
  - python:
      imports:
        - msglc
      pip_check: true

about:
  summary: binary json representation (msgpack or cbor) with lazy/partial loading containers
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/TLCFEM/msglc
  repository: https://github.com/TLCFEM/msglc

extra:
  recipe-maintainers:
    - jan-janssen
